#!/bin/bash
set -e

PREFIX='/usr/local'
NAME='mynethelptest'

cp -r . "$PREFIX/lib/$NAME"
chown -R root:root "$PREFIX/lib/$NAME"
chmod +x "$PREFIX/lib/$NAME/$NAME"

ln --symbolic --force "$PREFIX/lib/$NAME/$NAME" "$PREFIX/bin/"

mkdir -p "$HOME/.config/systemd/user"
ln --symbolic --force "$PREFIX/lib/$NAME/$NAME.service" "/etc/systemd/system/"

systemctl daemon-reload
