#!/bin/bash
set -e  # exit on error

NAME='mynethelptest'
SCRIPT="$(readlink -f "$0")"
DIR="$(dirname "$SCRIPT")"
cd $DIR  # cd to script directory


function launch() {
    node main.js
    launch  # relaunch on crash
}

if [ "$1" == '--tmux' ]; then
    if tmux has-session -t $NAME 2> /dev/null; then
        tmux kill-session -t $NAME  # kill session if running  
    fi
    tmux new-session -d -s $NAME "$SCRIPT"
    tmux set-option -t $NAME remain-on-exit on
else
    launch
fi
    
